name: vagelis
favicon: null
layout_spectrum: 0.548609169665724
typography_spectrum: 0.49385428219102323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2792037876788527
  lightness: 0.9327107956632972
  saturation: 0.8153900352772325
  rhythmicContrast: 0.6285195227246732
purpose: []
